### ISSUE TITLE
GL/glext.h not found

### ISSUE THREAD

**Issue by lkesteloot** [bradgrantham/apple2e#2]
Got this compile error:

    interface.cpp:18:10: fatal error: 'GL/glext.h' file not found
    #include <GL/glext.h>

I've installed glfw. Looks like I have the file here: `/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/System/Library/Frameworks/OpenGL.framework/Versions/A/Headers/glext.h`

I'm running Xcode 8.1.

**Comment by bradgrantham** [comment]
Fixed in e9453b7fe7dc6eefeeb0692a665776cf70cb85fd
