### ISSUE TITLE
Crash accessing past end of RAM

### ISSUE THREAD

**Issue by lkesteloot** [bradgrantham/apple2e#32]
An instructions can create an address that's past the 64k boundary. For example:

    STA (LL),Y

where LL points to zero page, which has an address like 0xFFFF, and Y is positive. This crashes the emulator in `MAINboard::write()` on this line:

    for(auto r : regions_by_page[addr / 256]) {

I assume that the fault is with fake6502 (in its `indy()` function perhaps). It should never pass you an address outside 64k, since the real 6502 couldn't do that.

**Comment by bradgrantham** [comment]
Should be worked around in 37864dea0fe30fb8d19ef5b4471923e2bec5b2a3.  @lkesteloot , please test.

**Comment by lkesteloot** [comment]
Seems to work. My test code was:

    asm("ldy #1");
    asm("sta $FFFF,y");
